### ISSUE TITLE
Action fails with `requests.exceptions.InvalidURL: Not supported URL scheme http+docker`

### ISSUE THREAD

**Issue by ameynert** [fulcrumgenomics/setup-latch#19]
`setup-latch` action is failing with an error which appears to be caused by the latest version of `requests`. Rolling back to `2.31.0` [seems to fix the problem for other people](https://github.com/docker/docker-py/issues/3256).

**Comment by luciakasman** [comment]
I've rolled back `requests` to `2.31.0` but now I have another error:

`TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'`

**Comment by nh13** [comment]
This should be fixed in latch `v2.45.2` as per private conversations with latch.  I'll add a link to the release or tag once those are made on https://github.com/latchbio/latch
